(source gnu)
(source melpa)
(source org)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smooth-scrolling")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "init-loader" :git "https://github.com/rkworks/init-loader.git")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-c-yasnippet")
(depends-on "shell-pop")
(depends-on "open-junk-file")
(depends-on "ag")
(depends-on "wgrep-ag")
(depends-on "helm-ag")
(depends-on "jump-char")
(depends-on "expand-region")
(depends-on "multiple-cursors")
;; (depends-on "pcre2el")
(depends-on "paredit")
(depends-on "rainbow-delimiters")
(depends-on "clj-refactor")
(depends-on "midje-mode")
(depends-on "auto-complete")
(depends-on "ace-jump-mode")
(depends-on "migemo")
(depends-on "quickrun")

(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "cider")
(depends-on "ac-cider")
(depends-on "align-cljlet")

(depends-on "undo-tree")
(depends-on "popwin")

(depends-on "powerline")

(depends-on "anzu")
(depends-on "ggtags")

(depends-on "php-mode")
(depends-on "inf-php")
(depends-on "yaml-mode")
(depends-on "scss-mode")
(depends-on "coffee-mode")
(depends-on "ruby-block")
(depends-on "ruby-end")
(depends-on "yari")
(depends-on "inf-ruby")
(depends-on "ruby-tools")

(depends-on "org-plus-contrib")

;; Themes
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "gruvbox-theme")
(depends-on "monokai-theme")
(depends-on "solarized-theme")
(depends-on "spacegray-theme")
(depends-on "zenburn-theme")

;; Experimental
(depends-on "e2wm")
